# Generated by Django 6.0 on 2026-01-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="student",
            name="absences",
            field=models.IntegerField(
                default=0, verbose_name="Number of school absences"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="family_relations",
            field=models.IntegerField(
                choices=[
                    (1, "Very bad"),
                    (2, "Bad"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=4,
                verbose_name="Quality of family relationships (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="father_education",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Primary (4th grade)"),
                    (2, "5th-9th grade"),
                    (3, "Secondary"),
                    (4, "Higher"),
                ],
                default=2,
                verbose_name="Father's education",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="free_time",
            field=models.IntegerField(
                choices=[
                    (1, "Very low"),
                    (2, "Low"),
                    (3, "Average"),
                    (4, "High"),
                    (5, "Very high"),
                ],
                default=3,
                verbose_name="Free time after school (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="go_out",
            field=models.IntegerField(
                choices=[
                    (1, "Very low"),
                    (2, "Low"),
                    (3, "Average"),
                    (4, "High"),
                    (5, "Very high"),
                ],
                default=3,
                verbose_name="Going out with friends (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="health_status",
            field=models.IntegerField(
                choices=[
                    (1, "Very bad"),
                    (2, "Bad"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Very good"),
                ],
                default=4,
                verbose_name="Current health status (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_education",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Primary (4th grade)"),
                    (2, "5th-9th grade"),
                    (3, "Secondary"),
                    (4, "Higher"),
                ],
                default=2,
                verbose_name="Mother's education",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="past_failures",
            field=models.IntegerField(
                default=0, verbose_name="Number of past class failures (0-4)"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="study_time",
            field=models.IntegerField(
                choices=[
                    (1, "<2 hours"),
                    (2, "2-5 hours"),
                    (3, "5-10 hours"),
                    (4, ">10 hours"),
                ],
                default=2,
                verbose_name="Weekly study time (1-4)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="success_probability",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Predicted success probability (0-1)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="travel_time",
            field=models.IntegerField(
                choices=[
                    (1, "<15 min"),
                    (2, "15-30 min"),
                    (3, "30-60 min"),
                    (4, ">60 min"),
                ],
                default=1,
                verbose_name="Home to school travel time (1-4)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="weekend_alcohol",
            field=models.IntegerField(
                choices=[
                    (1, "Very low"),
                    (2, "Low"),
                    (3, "Average"),
                    (4, "High"),
                    (5, "Very high"),
                ],
                default=1,
                verbose_name="Weekend alcohol consumption (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="workday_alcohol",
            field=models.IntegerField(
                choices=[
                    (1, "Very low"),
                    (2, "Low"),
                    (3, "Average"),
                    (4, "High"),
                    (5, "Very high"),
                ],
                default=1,
                verbose_name="Workday alcohol consumption (1-5)",
            ),
        ),
    ]
